AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template To Create a DynamoDB

Parameters:
  HashKeyElementName:
    Type: String
    Default: ISBN
    Description: Hash Key Name
  HashKeyElementType:
    Type: String
    Default: S
    Description: Hash Key Type
Resources:
  EmployeeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Books_Descriptions1
      AttributeDefinitions:
        - 
          AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
      KeySchema:
        - 
          AttributeName: !Ref HashKeyElementName
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: "vpc-ff35a094"
      GroupDescription: "Enable SSH access via port 22"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          Description: "Allowed from anywhere"
          FromPort: "22"
          ToPort: "22"
          IpProtocol: "tcp"
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t2.micro"
      SecurityGroups: [ !Ref 'InstanceSecurityGroup' ]
      KeyName: 'EC2Keypair'
      ImageId: ami-064446ad1d755489e
Outputs:
  Employee:
    Description: Table Created using this template.
    Value: !Ref EmployeeTable
