package com.example.demo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "books_descriptions")
public class Book {

    @DynamoDBHashKey(attributeName = "ISBN")
    @DynamoDBAutoGeneratedKey
    private String isbn;

    @DynamoDBAttribute(attributeName = "Description")
    private String description;

    @DynamoDBAttribute(attributeName = "Title")
    private String title;
}