name: "Deploy CloudFormation Stack"
on: 
  push:
    branches:
    - master
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-2
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
       name: MyStack
       template: template.yml
       no-fail-on-empty-changeset: "1"
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
         java-version: '11'
         distribution: 'adopt'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
          key: ${{ secrets.EC2KEYPAIR }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.KNOWN_HOSTS }} >> ~/.ssh/known_hosts

    - name: Copy jar to ec2
      run: scp 'target/awsdemo-0.0.1-SNAPSHOT.jar' ubuntu@${{ secrets.KNOWN_HOSTS }}:~/aws

    - name: Connect to ec2
      run: ssh ubuntu@${{ secrets.KNOWN_HOSTS }}

    - name: Connect to ec2
      run:  java -jar aws/awsdemo-0.0.1-SNAPSHOT.jar

