name: "Deploy CloudFormation Stack"
on: 
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mgenteluci/cloudformation-deploy-action@v1.4.0
      env:
        TEMPLATE: 'template.yml'
        AWS_STACK_NAME: 'my-stack'
        AWS_REGION: 'us-east-2'
        AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.SECRET_KEY}}
        AWS_DEPLOY_BUCKET: ${{secrets.BUCKET}}
