name: "Deploy CloudFormation Stack"
on: 
  push:
    branches:
    - master
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-2
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
       name: MyStack
       template: template.yml
       no-fail-on-empty-changeset: "1"
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
         java-version: '11'
         distribution: 'adopt'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
          key: ${{ secrets.EC2Keypair }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Copy jar to ec2
      uses: scp -i "target/awsdemo-0.0.1-SNAPSHOT.jar" ubuntu@ec2-3-12-34-6.us-east-2.compute.amazonaws.com:~/aws
